name: Build PR
on: [pull_request, workflow_dispatch]
env:
  BUILD_TYPE: Release
jobs:
  build-pr:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [RE2, RE2_TDB66, RE3, RE3_TDB67, RE4, RE7, RE7_TDB49, RE8, DMC5, MHRISE, SF6, DD2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDEVELOPER_MODE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}
          path: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
          if-no-files-found: error

